# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
case `uname` in
    Darwin)	
        export ZSH="/Users/ajrator/.oh-my-zsh"
	export PATH="/Users/ajrator/anaconda3/bin/:$PATH"
	export PATH="$PATH:`pwd`/flutter/bin"
	source ~/anaconda3/etc/profile.d/conda.sh
    ;;
    Linux)
        export ZSH="/home/ajrator/.oh-my-zsh"
	ZSH_DISABLE_COMPFIX=true
	export CUDA_VISIBLE_DEVICES=0
	export PATH=$PATH:~/.local/bin
	export LD_LIBRARY_PATH=/usr/lib/
	export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
	alias kubectx=kubectl ctx
	alias kubens=kubectl ns

	[[ -s /home/ajrator/.autojump/etc/profile.d/autojump.sh ]] && source /home/ajrator/.autojump/etc/profile.d/autojump.sh
	autoload -U compinit && compinit -u
	# >>> conda initialize >>>
	# !! Contents within this block are managed by 'conda init' !!
	__conda_setup="$('/home/ajrator/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
	    eval "$__conda_setup"
	else
	    if [ -f "/home/ajrator/miniconda3/etc/profile.d/conda.sh" ]; then
	# . "/home/ajrator/miniconda3/etc/profile.d/conda.sh"  # commented out by conda initialize
	    else
		export PATH="/home/ajrator/miniconda3/bin:$PATH"
	    fi
	fi
	unset __conda_setup
	# <<< conda initialize <<<
      cd ~
    ;;
esac

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"
# SPACESHIP_TIME_SHOW=true
# SPACESHIP_USER_SHOW=always
# SPACESHIP_HOST_SHOW=always
# SPACESHIP_PROMPT_SEPARATE_LINE=false
# SPACESHIP_PROMPT_ADD_NEWLINE=false
# SPACESHIP_PROMPT_PREFIXES_SHOW=false

# SPACESHIP_PROMPT_ORDER=(
#   time          # Time stampts section
#   user          # Username section
#   dir           # Current directory section
#   host          # Hostname section
#   git           # Git section (git_branch + git_status)
#   hg            # Mercurial section (hg_branch  + hg_status)
#   package       # Package version
#   node          # Node.js section
#   ruby          # Ruby section
#   elixir        # Elixir section
#   xcode         # Xcode section
#   swift         # Swift section
#   golang        # Go section
#   php           # PHP section
#   rust          # Rust section
#   haskell       # Haskell Stack section
#   julia         # Julia section
#   docker        # Docker section
#   aws           # Amazon Web Services section
#   venv          # virtualenv section
#   conda         # conda virtualenv section
#   pyenv         # Pyenv section
#   dotnet        # .NET section
#   ember         # Ember.js section
#   kubecontext   # Kubectl context section
#   exec_time     # Execution time
#   line_sep      # Line break
#   battery       # Battery level and status
#   jobs          # Background jobs indicator
#   exit_code     # Exit code section
#   char          # Prompt character
# )

plugins=(
  git
  golang
  zsh-autopair
  zsh-autosuggestions
  fast-syntax-highlighting
  zsh-vim-mode
)

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Automatically update without prompting.
DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

source $ZSH/oh-my-zsh.sh

# User configuration

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Syntax Highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

if [[ "$OSTYPE" == "darwin"* ]]; then
    # Autojump
    [ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
fi

# Syntax Highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Alias vim to utilize neovim
alias vim="nvim"

# Enable fzf to work with ripgrep
export FZF_DEFAULT_COMMAND="rg -uuu --files"
export FZF_DEFAULT_OPTS="--color='fg:249,hl:117,fg+:254,hl+:39'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Enable fzf to show previews of all files under directory
alias files="rg -uuu --files | fzf -i --preview='head -25 {+}'| tr -d '\n'"

# Select from parents
cdd() {
  local declare dirs=()
  get_parent_dirs() {
    if [[ -d "${1}" ]]; then dirs+=("$1"); else return; fi
    if [[ "${1}" == '/' ]]; then
      for _dir in "${dirs[@]}"; do echo $_dir; done
    else
      get_parent_dirs $(dirname "$1")
    fi
  }
  local DIR=$(get_parent_dirs $(realpath "${1:-$PWD}") | fzf --preview="/usr/local/bin/exa {}" --preview-window=down:30% --height=25% --layout=reverse)
  cd "$DIR"
}

# ^F to fuzz
___fsel() {
  local cmd="${FZF_CTRL_F_COMMAND:-"command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
    -o -type f -print \
    -o -type d -print \
    -o -type l -print 2> /dev/null | cut -b3-"}"
  setopt localoptions pipefail no_aliases 2> /dev/null
  eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_CTRL_F_OPTS" $(__fzfcmd) -m "$@" | while read item; do
    echo -n "${(q)item} "
  done
  local ret=$?
  echo
  return $ret
}

fzf-localfile-widget () {
  LBUFFER="${LBUFFER}$(___fsel)"
  local ret=$?
  zle reset-prompt
  return $ret
}

zle -N fzf-localfile-widget
bindkey '^z' fzf-localfile-widget

# Autojump
j() {
    if [[ "$#" -ne 0 ]]; then
        cd $(autojump $@)
        return
    fi
    cd "$(autojump -s | sort -k1gr | awk '$1 ~ /[0-9]:/ && $2 ~ /^\// { for (i=2; i<=NF; i++) { print $(i) } }' |  fzf --height 40% --reverse --inline-info)"
}

# Replace Tab Completion with FZF
source ~/.oh-my-zsh/custom/plugins/fzf-tab/fzf-tab.plugin.zsh
export FZF_TAB_OPTS=(-i -1 --cycle --layout=reverse --tiebreak=begin --bind tab:down,ctrl-j:accept --height=50%)

bindkey '^v' autosuggest-accept

alias v="vim +Files"
alias c="clear"

# Start zsh-vim-mode in INSERT mode
VIM_MODE_INITIAL_KEYMAP=viins

# Configure Go Path
export GOPATH=$HOME/go
export PATH=$PATH:$HOME/bin
